FORMAT: 1A

# VenuePay CreditLine

This API allows venue.com to process credit request from consumers via Magento.

## Credit Decision [/credit]

+ `JSON Request` consist of Customer, Order and Credit Request data.
+ `JSON Response` returns `true` or `false` based on request acceptance or rejection.

### Request for credit [POST]

+ Request (application/json)

    + Attributes (Request Credit Request)

+ Response 202 (application/json)

    + Headers

            Location: /credit/accepted/121142

    + Attributes (Request Credit Response Accepted)

+ Response 406 (application/json)

    + Headers

            Location: /credit/rejected/121142

    + Attributes (Request Credit Response Rejected)


### Charge credit account [GET]

+ Request (application/json)

        {
        }

+ Response 201 (application/json)

    + Headers

            Location: /xxxx

    + Body

            {
            }


## Credit Line [/credit/line]

Credit line description

### Remove Credit Line [DELETE]

+ Response 200 (application/json)

        [
        ]

### Update Credit Line [POST]

+ Response 200 (application/json)

        [
        ]

### Validate Credit Line [GET]

+ Response 200 (application/json)

        [
        ]
            
# Data Structures

## Request Credit Request
+ name (name) - Customer name
+ email: `adnan.shahzad@progos.org` (string, required) - Customer email address
+ gender: `1` (number, required) - Customer gender 1: Male, 2: Female, 3: Not specified
+ group: `1` (number, required) - Customer group
+ store: `1` (number, required) - Associated customer website
+ tax: `DTS-34441-3` (string, required) - Customer Tax/Vat number
+ dob: `12/15/2000` (string, required)  - Customer date of birth
+ addresses (addresses) - Customer addresses

### name
+ prefix: `Syed` (string, optional) - Prefix of customer name
+ first: `Adnan` (string, required) - Customer first Name
+ middle: `` (string, optional) - Customer middle name
+ last: `Shahzad` (string, required) - Customer last Name
+ suffix: `Bukhari` (string, optional) - Initial of customer name

### addresses
+ shipping (all addresses) - Shipping address of customer
+ billing (all addresses) - Billing address of customer

### all addresses
+ name (name)
+ company: `Progostech` (string, optional) - Company name
+ address (array, required) - Street address
    - (enum)
        - firstField
        - secondField
        - extraField
        - dummyField
        
+ city: `Dubai` (string, optional) - City name
+ country: `AE` (string, optional) - Country code
+ state: `Progostech` (string, optional) - State/Province
+ zip: `12445` (string, optional) - Zip/Postal code
+ phone: `+123456789` (string, optional) - Phone number
+ tax: `DTS-34441-3` (string, required) - Tax/Vat number

## Request Credit Response Accepted
+ error: `false` (boolean, required) - Response status
+ token: `5qYHzcZX4ejeUE3yqtHVRDW73znegWTI` (string, required) - VenueAPI token
+ transaction_id: `121142` (string, required) - ID of the transaction
+ application_id: `FX20-119` (string, required) - Customer contract or application ID
+ balance: `1150.4` (number, required) - Remaining amount in vault
+ message: `Your loan request is successfully approved` (string, required) - Message/Remarks

## Request Credit Response Rejected
+ error: `true` (boolean, required) - Response status
+ token: `5qYHzcZX4ejeUE3yqtHVRDW73znegWTI` (string, required) - VenueAPI token
+ requested_amount: `1200` (number, required) - Total loan amount requested for customer
+ message: `Cannot authorize request` (string, required) - Message/Remarks